
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.gunsmithcognitis.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.Item;

import net.mcreator.gunsmithcognitis.item.WheellockgunkitItem;
import net.mcreator.gunsmithcognitis.item.WheellockSportingRifleItem;
import net.mcreator.gunsmithcognitis.item.WheellockPistolItem;
import net.mcreator.gunsmithcognitis.item.WheellockMusketItem;
import net.mcreator.gunsmithcognitis.item.WheellockKalthoffRepeaterItem;
import net.mcreator.gunsmithcognitis.item.WheellockCarbineItem;
import net.mcreator.gunsmithcognitis.item.ThreeeyegunItem;
import net.mcreator.gunsmithcognitis.item.TanegashimaItem;
import net.mcreator.gunsmithcognitis.item.StonepikeItem;
import net.mcreator.gunsmithcognitis.item.StonehalberdItem;
import net.mcreator.gunsmithcognitis.item.SmoothborebarrelItem;
import net.mcreator.gunsmithcognitis.item.RockItem;
import net.mcreator.gunsmithcognitis.item.RiflingtoolItem;
import net.mcreator.gunsmithcognitis.item.RifledbarrelItem;
import net.mcreator.gunsmithcognitis.item.RevolverDrumItem;
import net.mcreator.gunsmithcognitis.item.RamrodItem;
import net.mcreator.gunsmithcognitis.item.PaperCartidgeSmallAmmoItem;
import net.mcreator.gunsmithcognitis.item.PaperCartidgeAmmoItem;
import net.mcreator.gunsmithcognitis.item.NockVolleyGunItem;
import net.mcreator.gunsmithcognitis.item.NockVolleyGunFrontComponentItem;
import net.mcreator.gunsmithcognitis.item.NetheritehalberdItem;
import net.mcreator.gunsmithcognitis.item.NetheritePikeItem;
import net.mcreator.gunsmithcognitis.item.MusketballItem;
import net.mcreator.gunsmithcognitis.item.MusketBallProjectileItem;
import net.mcreator.gunsmithcognitis.item.MortarballItem;
import net.mcreator.gunsmithcognitis.item.MatchlockrepairItem;
import net.mcreator.gunsmithcognitis.item.MatchlockWallGunItem;
import net.mcreator.gunsmithcognitis.item.MatchlockSnaphanceMusketItem;
import net.mcreator.gunsmithcognitis.item.MatchlockBlunderbussItem;
import net.mcreator.gunsmithcognitis.item.MatchlockAxePistolItem;
import net.mcreator.gunsmithcognitis.item.MatchlockArquebusItem;
import net.mcreator.gunsmithcognitis.item.JezailmusketItem;
import net.mcreator.gunsmithcognitis.item.IronpikeItem;
import net.mcreator.gunsmithcognitis.item.IronhalberdItem;
import net.mcreator.gunsmithcognitis.item.HandgunneItem;
import net.mcreator.gunsmithcognitis.item.HandBombItem;
import net.mcreator.gunsmithcognitis.item.GoldpikeItem;
import net.mcreator.gunsmithcognitis.item.GoldhalberdItem;
import net.mcreator.gunsmithcognitis.item.FlintlockmusketgoldItem;
import net.mcreator.gunsmithcognitis.item.FlintlockmusketbayonetItem;
import net.mcreator.gunsmithcognitis.item.FlintlockmusketItem;
import net.mcreator.gunsmithcognitis.item.FlintlockgunkitItem;
import net.mcreator.gunsmithcognitis.item.FlintlockRifledCarbineItem;
import net.mcreator.gunsmithcognitis.item.FlintlockPistolItem;
import net.mcreator.gunsmithcognitis.item.FlintlockPistolGoldItem;
import net.mcreator.gunsmithcognitis.item.FlintlockPepperboxItem;
import net.mcreator.gunsmithcognitis.item.FlintlockPepperboxCarbineItem;
import net.mcreator.gunsmithcognitis.item.FlintlockLorenzoniRepeaterItem;
import net.mcreator.gunsmithcognitis.item.FlintlockHeavyDragoonPistolItem;
import net.mcreator.gunsmithcognitis.item.FlintlockHandMortarItem;
import net.mcreator.gunsmithcognitis.item.FlintlockDoubleBarrelPistolItem;
import net.mcreator.gunsmithcognitis.item.FlintlockDoubleBarrelMusketItem;
import net.mcreator.gunsmithcognitis.item.FlintlockCollierRevolvingCarbineItem;
import net.mcreator.gunsmithcognitis.item.FlintlockCollierRevolverItem;
import net.mcreator.gunsmithcognitis.item.FlintlockBlueprintItem;
import net.mcreator.gunsmithcognitis.item.FlintlockAsumetteRifledWallGunItem;
import net.mcreator.gunsmithcognitis.item.FergusonRifleItem;
import net.mcreator.gunsmithcognitis.item.DivineFiveThunderMachineItem;
import net.mcreator.gunsmithcognitis.item.DiamondhalberdItem;
import net.mcreator.gunsmithcognitis.item.DiamondPikeItem;
import net.mcreator.gunsmithcognitis.item.CuirassItem;
import net.mcreator.gunsmithcognitis.item.CrudeSmoothborebarrelItem;
import net.mcreator.gunsmithcognitis.item.CavalrySabreItem;
import net.mcreator.gunsmithcognitis.GunsmithCognitisMod;

public class GunsmithCognitisModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, GunsmithCognitisMod.MODID);
	public static final RegistryObject<Item> MUSKETBALL = REGISTRY.register("musketball", () -> new MusketballItem());
	public static final RegistryObject<Item> PAPER_CARTIDGE_SMALL_AMMO = REGISTRY.register("paper_cartidge_small_ammo", () -> new PaperCartidgeSmallAmmoItem());
	public static final RegistryObject<Item> PAPER_CARTIDGE_AMMO = REGISTRY.register("paper_cartidge_ammo", () -> new PaperCartidgeAmmoItem());
	public static final RegistryObject<Item> MORTARBALL = REGISTRY.register("mortarball", () -> new MortarballItem());
	public static final RegistryObject<Item> RAMROD = REGISTRY.register("ramrod", () -> new RamrodItem());
	public static final RegistryObject<Item> RIFLINGTOOL = REGISTRY.register("riflingtool", () -> new RiflingtoolItem());
	public static final RegistryObject<Item> CRUDE_SMOOTHBOREBARREL = REGISTRY.register("crude_smoothborebarrel", () -> new CrudeSmoothborebarrelItem());
	public static final RegistryObject<Item> SMOOTHBOREBARREL = REGISTRY.register("smoothborebarrel", () -> new SmoothborebarrelItem());
	public static final RegistryObject<Item> RIFLEDBARREL = REGISTRY.register("rifledbarrel", () -> new RifledbarrelItem());
	public static final RegistryObject<Item> REVOLVER_DRUM = REGISTRY.register("revolver_drum", () -> new RevolverDrumItem());
	public static final RegistryObject<Item> MATCHLOCKGUNKIT = REGISTRY.register("matchlockgunkit", () -> new MatchlockrepairItem());
	public static final RegistryObject<Item> WHEELLOCKGUNKIT = REGISTRY.register("wheellockgunkit", () -> new WheellockgunkitItem());
	public static final RegistryObject<Item> FLINTLOCKGUNKIT = REGISTRY.register("flintlockgunkit", () -> new FlintlockgunkitItem());
	public static final RegistryObject<Item> HANDGUNNE = REGISTRY.register("handgunne", () -> new HandgunneItem());
	public static final RegistryObject<Item> THREEEYEGUN = REGISTRY.register("threeeyegun", () -> new ThreeeyegunItem());
	public static final RegistryObject<Item> HAND_BOMB = REGISTRY.register("hand_bomb", () -> new HandBombItem());
	public static final RegistryObject<Item> MATCHLOCK_ARQUEBUS = REGISTRY.register("matchlock_arquebus", () -> new MatchlockArquebusItem());
	public static final RegistryObject<Item> MATCHLOCK_BLUNDERBUSS = REGISTRY.register("matchlock_blunderbuss", () -> new MatchlockBlunderbussItem());
	public static final RegistryObject<Item> MATCHLOCK_WALL_GUN = REGISTRY.register("matchlock_wall_gun", () -> new MatchlockWallGunItem());
	public static final RegistryObject<Item> MATCHLOCK_AXE_PISTOL = REGISTRY.register("matchlock_axe_pistol", () -> new MatchlockAxePistolItem());
	public static final RegistryObject<Item> TANEGASHIMA = REGISTRY.register("tanegashima", () -> new TanegashimaItem());
	public static final RegistryObject<Item> MATCHLOCK_SNAPHANCE_MUSKET = REGISTRY.register("matchlock_snaphance_musket", () -> new MatchlockSnaphanceMusketItem());
	public static final RegistryObject<Item> WHEELLOCK_PISTOL = REGISTRY.register("wheellock_pistol", () -> new WheellockPistolItem());
	public static final RegistryObject<Item> WHEELLOCK_CARBINE = REGISTRY.register("wheellock_carbine", () -> new WheellockCarbineItem());
	public static final RegistryObject<Item> WHEELLOCK_MUSKET = REGISTRY.register("wheellock_musket", () -> new WheellockMusketItem());
	public static final RegistryObject<Item> WHEELLOCK_SPORTING_RIFLE = REGISTRY.register("wheellock_sporting_rifle", () -> new WheellockSportingRifleItem());
	public static final RegistryObject<Item> FLINTLOCK_BLUEPRINT = REGISTRY.register("flintlock_blueprint", () -> new FlintlockBlueprintItem());
	public static final RegistryObject<Item> CAVALRY_SABRE = REGISTRY.register("cavalry_sabre", () -> new CavalrySabreItem());
	public static final RegistryObject<Item> FLINTLOCKMUSKET = REGISTRY.register("flintlockmusket", () -> new FlintlockmusketItem());
	public static final RegistryObject<Item> FLINTLOCKMUSKETBAYONET = REGISTRY.register("flintlockmusketbayonet", () -> new FlintlockmusketbayonetItem());
	public static final RegistryObject<Item> FLINTLOCKMUSKETGOLD = REGISTRY.register("flintlockmusketgold", () -> new FlintlockmusketgoldItem());
	public static final RegistryObject<Item> FLINTLOCK_PISTOL = REGISTRY.register("flintlock_pistol", () -> new FlintlockPistolItem());
	public static final RegistryObject<Item> FLINTLOCK_PISTOL_GOLD = REGISTRY.register("flintlock_pistol_gold", () -> new FlintlockPistolGoldItem());
	public static final RegistryObject<Item> FLINTLOCK_ASUMETTE_RIFLED_WALL_GUN = REGISTRY.register("flintlock_asumette_rifled_wall_gun", () -> new FlintlockAsumetteRifledWallGunItem());
	public static final RegistryObject<Item> FLINTLOCK_RIFLED_CARBINE = REGISTRY.register("flintlock_rifled_carbine", () -> new FlintlockRifledCarbineItem());
	public static final RegistryObject<Item> JEZAILMUSKET = REGISTRY.register("jezailmusket", () -> new JezailmusketItem());
	public static final RegistryObject<Item> FLINTLOCK_DOUBLE_BARREL_PISTOL = REGISTRY.register("flintlock_double_barrel_pistol", () -> new FlintlockDoubleBarrelPistolItem());
	public static final RegistryObject<Item> FLINTLOCK_DOUBLE_BARREL_MUSKET = REGISTRY.register("flintlock_double_barrel_musket", () -> new FlintlockDoubleBarrelMusketItem());
	public static final RegistryObject<Item> FLINTLOCK_PEPPERBOX = REGISTRY.register("flintlock_pepperbox", () -> new FlintlockPepperboxItem());
	public static final RegistryObject<Item> FLINTLOCK_HAND_MORTAR = REGISTRY.register("flintlock_hand_mortar", () -> new FlintlockHandMortarItem());
	public static final RegistryObject<Item> FLINTLOCK_LORENZONI_REPEATER = REGISTRY.register("flintlock_lorenzoni_repeater", () -> new FlintlockLorenzoniRepeaterItem());
	public static final RegistryObject<Item> FLINTLOCK_PEPPERBOX_CARBINE = REGISTRY.register("flintlock_pepperbox_carbine", () -> new FlintlockPepperboxCarbineItem());
	public static final RegistryObject<Item> WHEELLOCK_KALTHOFF_REPEATER = REGISTRY.register("wheellock_kalthoff_repeater", () -> new WheellockKalthoffRepeaterItem());
	public static final RegistryObject<Item> DIVINE_FIVE_THUNDER_MACHINE = REGISTRY.register("divine_five_thunder_machine", () -> new DivineFiveThunderMachineItem());
	public static final RegistryObject<Item> FLINTLOCK_HEAVY_DRAGOON_PISTOL = REGISTRY.register("flintlock_heavy_dragoon_pistol", () -> new FlintlockHeavyDragoonPistolItem());
	public static final RegistryObject<Item> NOCK_VOLLEY_GUN_FRONT_COMPONENT = REGISTRY.register("nock_volley_gun_front_component", () -> new NockVolleyGunFrontComponentItem());
	public static final RegistryObject<Item> NOCK_VOLLEY_GUN = REGISTRY.register("nock_volley_gun", () -> new NockVolleyGunItem());
	public static final RegistryObject<Item> FLINTLOCK_COLLIER_REVOLVER = REGISTRY.register("flintlock_collier_revolver", () -> new FlintlockCollierRevolverItem());
	public static final RegistryObject<Item> FLINTLOCK_COLLIER_REVOLVING_CARBINE = REGISTRY.register("flintlock_collier_revolving_carbine", () -> new FlintlockCollierRevolvingCarbineItem());
	public static final RegistryObject<Item> FERGUSON_RIFLE = REGISTRY.register("ferguson_rifle", () -> new FergusonRifleItem());
	public static final RegistryObject<Item> MUSKET_BALL_PROJECTILE = REGISTRY.register("musket_ball_projectile", () -> new MusketBallProjectileItem());
	public static final RegistryObject<Item> ROCK = REGISTRY.register("rock", () -> new RockItem());
	public static final RegistryObject<Item> STONEPIKE = REGISTRY.register("stonepike", () -> new StonepikeItem());
	public static final RegistryObject<Item> IRONPIKE = REGISTRY.register("ironpike", () -> new IronpikeItem());
	public static final RegistryObject<Item> GOLDPIKE = REGISTRY.register("goldpike", () -> new GoldpikeItem());
	public static final RegistryObject<Item> DIAMONDPIKE = REGISTRY.register("diamondpike", () -> new DiamondPikeItem());
	public static final RegistryObject<Item> NETHERITEPIKE = REGISTRY.register("netheritepike", () -> new NetheritePikeItem());
	public static final RegistryObject<Item> STONEHALBERD = REGISTRY.register("stonehalberd", () -> new StonehalberdItem());
	public static final RegistryObject<Item> IRONHALBERD = REGISTRY.register("ironhalberd", () -> new IronhalberdItem());
	public static final RegistryObject<Item> GOLDHALBERD = REGISTRY.register("goldhalberd", () -> new GoldhalberdItem());
	public static final RegistryObject<Item> DIAMONDHALBERD = REGISTRY.register("diamondhalberd", () -> new DiamondhalberdItem());
	public static final RegistryObject<Item> NETHERITEHALBERD = REGISTRY.register("netheritehalberd", () -> new NetheritehalberdItem());
	public static final RegistryObject<Item> CUIRASS_CHESTPLATE = REGISTRY.register("cuirass_chestplate", () -> new CuirassItem.Chestplate());
}
